pygmentize -O "style=monokai,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_monokai.png andy.clj
pygmentize -O "style=manni,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_manni.png andy.clj
pygmentize -O "style=rrt,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_rrt.png andy.clj
pygmentize -O "style=perldoc,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_perldoc.png andy.clj
pygmentize -O "style=borland,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_borland.png andy.clj
pygmentize -O "style=colorful,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_colorful.png andy.clj
pygmentize -O "style=default,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_default.png andy.clj
pygmentize -O "style=murphy,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_murphy.png andy.clj
pygmentize -O "style=vs,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_vs.png andy.clj
pygmentize -O "style=trac,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_trac.png andy.clj
pygmentize -O "style=tango,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_tango.png andy.clj
pygmentize -O "style=fruity,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_fruity.png andy.clj
pygmentize -O "style=autumn,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_autumn.png andy.clj
pygmentize -O "style=bw,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_bw.png andy.clj
pygmentize -O "style=emacs,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_emacs.png andy.clj
pygmentize -O "style=vim,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_vim.png andy.clj
pygmentize -O "style=pastie,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_pastie.png andy.clj
pygmentize -O "style=friendly,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_friendly.png andy.clj
pygmentize -O "style=native,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_native.png andy.clj
pygmentize -O "style=solarizeddark,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_solarizeddark.png andy.clj
pygmentize -O "style=solarizedlight,fontface=Courier Bold,font_size=36,line_numbers=False" -o andy_solarizedlight.png andy.clj
